INSERT INTO dvds (TITLE, DESCRIPTION) VALUES ('Title', 'Description');
INSERT INTO dvds (TITLE, DESCRIPTION) VALUES ('T', 'Desc');
INSERT INTO dvds (TITLE, DESCRIPTION) VALUES ('Test title', 'test another description');
INSERT INTO dvds (TITLE, DESCRIPTION) VALUES ('NEW', 'BOOMING');
